// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxcxjkxylxicibwuowqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4Y3hqa3h5bHhpY2lid3Vvd3FxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxODI2MTcsImV4cCI6MjA2Mzc1ODYxN30.pbiM6L2c6IgrU_SGTMww9Wa2TxO9QSsQRJJX4BW9SxA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);